# NumPy Indexing and Selection

How to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Reset array
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [12]:
arr = np.arange(0,11)

#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr_copy[2:5] = 99
arr_copy

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [17]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [18]:
# Getting individual element value
arr_2d[1,0]

20

In [19]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [20]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [21]:
arr_2d[-1]

array([35, 40, 45])

In [22]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [37]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
#Length of array
arr_length = arr2d.shape[0]
arr_length

10

In [39]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i*3 + 1
    
arr2d

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [19., 19., 19., 19., 19., 19., 19., 19., 19., 19.],
       [22., 22., 22., 22., 22., 22., 22., 22., 22., 22.],
       [25., 25., 25., 25., 25., 25., 25., 25., 25., 25.],
       [28., 28., 28., 28., 28., 28., 28., 28., 28., 28.]])

In [40]:
#Loop over the columns
#for i in range(arr2d.shape[1]):
#    arr2d[:, i] = i*3 + 1
    
#arr2d

Fancy indexing allows the following

In [41]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[19., 19., 19., 19., 19., 19., 19., 19., 19., 19.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [22., 22., 22., 22., 22., 22., 22., 22., 22., 22.]])

In [42]:
arr2d[:, [6,4,2,7]]

array([[ 1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.],
       [ 7.,  7.,  7.,  7.],
       [10., 10., 10., 10.],
       [13., 13., 13., 13.],
       [16., 16., 16., 16.],
       [19., 19., 19., 19.],
       [22., 22., 22., 22.],
       [25., 25., 25., 25.],
       [28., 28., 28., 28.]])

In [28]:
arr2d[[0,1,3,4], [2]]

array([ 1.,  4., 10., 13.])

In [29]:
arr2d[:,[2,4,6,8]]

array([[ 1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.],
       [ 7.,  7.,  7.,  7.],
       [10., 10., 10., 10.],
       [13., 13., 13., 13.],
       [16., 16., 16., 16.],
       [19., 19., 19., 19.],
       [22., 22., 22., 22.],
       [25., 25., 25., 25.],
       [28., 28., 28., 28.]])

In [30]:
#arr2d[[2,3], [2,4,6,8]] --not possible
arr2d[:,[2,4,6,8]][[2,3]]

array([[ 7.,  7.,  7.,  7.],
       [10., 10., 10., 10.]])

In [31]:
arr2d[:,[2,4,6,8]][[1,3,4]]

array([[ 4.,  4.,  4.,  4.],
       [10., 10., 10., 10.],
       [13., 13., 13., 13.]])

In [32]:
#List cannot choose any order like array, we need to work around with loop or change list to array
lst = [1,2,3,4,5,7,8,6]
lst[[0,3,4]]

TypeError: list indices must be integers or slices, not list

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>2]

In [ ]:
x = 2
arr[arr>x]

# Great Job!
