## Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr + arr1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
np.add(arr, arr1)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
arr * arr1

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [15]:
arr/arr

/var/folders/yz/qdg2wztx1m79ghkm18b03dxm0000gn/T/ipykernel_3472/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
1/arr

/var/folders/yz/qdg2wztx1m79ghkm18b03dxm0000gn/T/ipykernel_3472/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [18]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal array functions

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [22]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [24]:
np.max(arr)

9

In [25]:
np.min(arr)

0

In [26]:
np.log(arr)

/var/folders/yz/qdg2wztx1m79ghkm18b03dxm0000gn/T/ipykernel_3472/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])