In [9]:
import numpy as np

## Creating Numpy array

In [4]:
my_list = [1,2,3]

In [6]:
my_list_times2 = [x*2 for x in my_list]
my_list_times2

[2, 4, 6]

In [11]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [27]:
list_in_list = [[1,2,3,1], [4,5,6,3], [4,5,7,2]]
list_in_list

[[1, 2, 3, 1], [4, 5, 6, 3], [4, 5, 7, 2]]

In [28]:
arr2 = np.array(list_in_list)
arr2

array([[1, 2, 3, 1],
       [4, 5, 6, 3],
       [4, 5, 7, 2]])

## Built-in Methods

In [29]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros and ones

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [38]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random

In [42]:
np.random.rand(5)

array([0.32684823, 0.87137171, 0.04342851, 0.61705807, 0.78677001])

In [43]:
np.random.randn(2)

array([-0.06292285,  0.45323654])

In [46]:
np.random.randint(low = 1, size = 10, high = 100)

array([24, 42, 36, 56, 66, 26, 12, 99, 83, 91])

## Atributes and Methods

In [47]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
ranarr

array([41,  7, 37, 19, 37,  9, 20, 25, 14, 37])

**reshape**

In [56]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr.shape

(25,)

**max,...**

In [57]:
ranarr

array([41,  7, 37, 19, 37,  9, 20, 25, 14, 37])

In [58]:
ranarr.max()

41

In [59]:
ranarr.min()

7

In [60]:
ranarr.argmax()

0

In [61]:
ranarr.argmin()

1

In [63]:
arr.shape

(25,)

In [64]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [65]:
arr.reshape(1,25).shape

(1, 25)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr.dtype

dtype('int64')