## Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr_1 = np.arange(2,11)
arr_1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr_1[2]

4

In [8]:
arr_1[8]

10

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[:4]

array([0, 1, 2, 3])

In [13]:
arr[-4:]

array([ 7,  8,  9, 10])

## Broadcasting

In [29]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
slice = arr[:4]
slice

array([0, 1, 2, 3])

In [32]:
slice[:2] = 99
slice

array([99, 99,  2,  3])

In [33]:
arr

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr_copy = arr.copy()
arr_copy

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr_copy[2:5] = 33
arr_copy

array([99, 99, 33, 33, 33,  5,  6,  7,  8,  9, 10])

In [41]:
arr

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Indexing a 2D array**

In [42]:
arr_2d = np.array(([1,2,3], [4,5,6], [7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr_2d[1][1]

5

In [45]:
arr_2d[1,1]

5

In [46]:
arr_2d[1,2]

6

In [48]:
arr_2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [51]:
arr_2d[1:, :2]

array([[4, 5],
       [7, 8]])

In [54]:
arr_2d[2]

array([7, 8, 9])

## Fancy Indexing

In [96]:
arr2d = np.zeros((10,8))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [94]:
#arr_len = arr2d.shape[0]
#list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [91]:
#arr2d[0] = 10
#arr2d

In [92]:
#arr2d[5] = 5
#arr2d

In [97]:
range_loop = [0, 1, 2]
for i in range_loop:
    arr2d[i] = i+3
arr2d

array([[3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [98]:
arr2d = np.ones((4,5))
arr2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
#arr2d.shape[0]
seq_ramge = range(arr2d.shape[0])
seq_ramge

range(0, 4)

In [107]:
for i in seq_ramge:
    print(i*3 + 1)

1
4
7
10


In [104]:
seq_ramge

range(0, 4)

In [99]:
seq = [0, 1, 2, 3]
for i in seq:
    arr2d[i] = i*3 + 1
arr2d

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 7.,  7.,  7.,  7.,  7.],
       [10., 10., 10., 10., 10.]])