## Indexing and Selection

In [7]:
import numpy as np

In [8]:
arr = np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[8]

8

In [11]:
arr_1 = np.arange(2,11)
arr_1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr_1[2]

4

In [13]:
arr_1[8]

10

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[:4]

array([0, 1, 2, 3])

In [16]:
arr[-4:]

array([ 7,  8,  9, 10])

## Broadcasting

In [17]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice = arr[:4]
slice

array([0, 1, 2, 3])

In [19]:
slice[:2] = 99
slice

array([99, 99,  2,  3])

In [20]:
arr

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()
arr_copy

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr_copy[2:5] = 33
arr_copy

array([99, 99, 33, 33, 33,  5,  6,  7,  8,  9, 10])

In [24]:
arr

array([99, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Indexing a 2D array**

In [25]:
arr_2d = np.array(([1,2,3], [4,5,6], [7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr_2d[1][1]

5

In [27]:
arr_2d[1,1]

5

In [28]:
arr_2d[1,2]

6

In [29]:
arr_2d[1:, 1:]

array([[5, 6],
       [8, 9]])

In [30]:
arr_2d[1:, :2]

array([[4, 5],
       [7, 8]])

In [31]:
arr_2d[2]

array([7, 8, 9])

## Fancy Indexing

In [32]:
arr2d = np.zeros((10,8))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
#arr_len = arr2d.shape[0]
#list(range(10))

In [34]:
#arr2d[0] = 10
#arr2d

In [35]:
#arr2d[5] = 5
#arr2d

In [36]:
range_loop = [0, 1, 2]
for i in range_loop:
    arr2d[i] = i+3
arr2d

array([[3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
arr2d = np.ones((4,5))
arr2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [77]:
for i in range(arr2d.shape[1]):
    arr2d[:, i] = i*3+ 2
arr2d

array([[ 2.,  5.,  8., 11., 14.],
       [ 2.,  5.,  8., 11., 14.],
       [ 2.,  5.,  8., 11., 14.],
       [ 2.,  5.,  8., 11., 14.]])

In [74]:
arr2d[:, [4, 3, 0, 1]]

array([[14., 11.,  2.,  5.],
       [14., 11.,  2.,  5.],
       [14., 11.,  2.,  5.],
       [14., 11.,  2.,  5.]])

In [75]:
arr3 = np.ones((4,5))
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
for i in range(arr2d.shape[0]):
    arr3[i] = i*3+ 2
arr3

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 5.,  5.,  5.,  5.,  5.],
       [ 8.,  8.,  8.,  8.,  8.],
       [11., 11., 11., 11., 11.]])

In [79]:
arr3[[3, 2, 0, 1], :]

array([[11., 11., 11., 11., 11.],
       [ 8.,  8.,  8.,  8.,  8.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 5.,  5.,  5.,  5.,  5.]])

In [97]:
arr_4 = np.array(([1,2,3,7], [4,5,6,10], [7,8,9,11], [4,18,19,21], [24,138,149,251], [14,438,169,271])).transpose()
arr_4

array([[  1,   4,   7,   4,  24,  14],
       [  2,   5,   8,  18, 138, 438],
       [  3,   6,   9,  19, 149, 169],
       [  7,  10,  11,  21, 251, 271]])

In [102]:
arr_4[:, [0, 2, 4]]

array([[  1,   7,  24],
       [  2,   8, 138],
       [  3,   9, 149],
       [  7,  11, 251]])

In [105]:
odd_lst = []
for ind in range(arr_4.shape[1]):
    if ind%2 != 0:
        odd_lst.append(ind)
odd_lst

[1, 3, 5]

In [106]:
arr_4[:, odd_lst]

array([[  4,   4,  14],
       [  5,  18, 438],
       [  6,  19, 169],
       [ 10,  21, 271]])

In [107]:
arr_4

array([[  1,   4,   7,   4,  24,  14],
       [  2,   5,   8,  18, 138, 438],
       [  3,   6,   9,  19, 149, 169],
       [  7,  10,  11,  21, 251, 271]])

In [117]:
new_arr = arr_4[:, [2,4,5]]
new_arr[1:3]

array([[  8, 138, 438],
       [  9, 149, 169]])

In [118]:
arr_4[:, [2,4,5]][1:3]

array([[  8, 138, 438],
       [  9, 149, 169]])

In [119]:
arr_4[[1,2], [2,4,5]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

## Selection

In [128]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [122]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [126]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
arr2 = np.arange(1,11).reshape(2,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2[0, :] 